### PR TITLE
Add Alpine building dependencies

### PR DESCRIPTION
**Pull request by lrinQVQ**
linux-headers supply netfilter headers
fix https://github.com/shadowsocks/simple-obfs/issues/76
fix https://github.com/shadowsocks/simple-obfs/issues/62

### CODE REVIEW

**Comment by debiansid** [comment]
and my goal is make alpine package of simple-obfs, but for now, I only saw it on debian/arch , can you help on that?

**Comment by lrinQVQ** [comment]
ok~ i try to create APKBUILD,please wait

**Comment by lrinQVQ** [comment]
@debiansid https://github.com/shadowsocks/simple-obfs/pull/107/commits/745fefa44fc99a306699780ccaf51f13a1a5c08a

**Comment by lrinQVQ** [comment]
@debiansid https://github.com/shadowsocks/simple-obfs/pull/107/commits/a01eecc7dd3553501d22f90896619c7abeadbee8

**Comment by lrinQVQ** [comment]
emmm indeed can't work with shadowsocks-libev 3.1.0,so... @madeye although very few changes after 0.3 release actually0.0 but ... to many people needs this,maybe you can releases 0.3.1?

**Comment by debiansid** [comment]
ok then, let's wait madeye release new version.

**Pull request merged**
