### PR TITLE
Make the HTTP obfuscation work behind an NGINX reverse proxy

### PR DESCRIPTION
**Pull request by t123yh**
Changed the following things:
1. Added `Content-Length` header to the initial HTTP request.
2. Make the `http` obfuscator respond immediately after request.

### CODE REVIEW

**Comment by madeye** [comment]
Cool! Have you tested it with Nginx?

**Comment by t123yh** [comment]
@madeye Tested (only stand-alone mode), with common WebSocket reverse proxy configuration.

**Comment by madeye** [comment]
Merged. Thanks!

**Comment by t123yh** [comment]
@madeye Note that this breaks the compatibility with the previous version (because it will send a response with empty content which old code cannot handle), so I think you would better bump the version.

**Comment by madeye** [comment]
Could you make this feature optiomal? Add a command line argument to control it.

**Comment by t123yh** [comment]
In my opinion, this is a 'bug fix' rather than a feature. An HTTP request will usually have its reply back immediately, won't it?

**Comment by madeye** [comment]
I don't think so. Actually a server can reply whenever it likes. Imagine a busy server with hundreds of thousands of connections, a delay reply is expected.

**Comment by t123yh** [comment]
Okay, then let's make this functionality optional. I'll look at this later.

**Comment by madeye** [comment]
Never mind. I've added it via 77136e8

**Comment by debiansid** [comment]
So this is not working with plugin mode , right?

**Comment by Amonhuz** [comment]
@t123yh 你好，请问你那里nginx转发可以正常使用吗？
我配好后，在iOS的surge上只能测速，其他应用无法使用代理；在windows上的4.0.9客户端+0.0.5obfs只能更新pac，其他应用无法使用代理。

obfs试过stand alone模式和plugin模式。
nginx配置试过这两种，能和你的配置对比一下么？
谢谢！

nginx配置
server {
    listen 80;
    server_name ;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "upgrade";
        if (\$http_upgrade = "websocket") {
            proxy_pass http://127.0.0.1:9999;
        }
    }
}

和

server {
    listen 80;
    server_name 

    location = / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:9999;
    }
}

shadowsocks配置
{
 "server": "127.0.0.1",
 "server_port": 9999,
 "password": "password",
 "plugin": "obfs-server",
 "plugin_opts": "obfs=http",
 "timeout": 300,
 "method": "xchacha20-ietf-poly1305",
 "worker": 1
}

**Comment by Amonhuz** [comment]
@t123yh  你好，请问你那里nginx转发可以正常使用吗？
我配好后，在iOS的surge上只能测速，其他应用无法使用代理；在windows上的4.0.9客户端+0.0.5obfs只能更新pac，其他应用无法使用代理。
nginx日志有很多499、502错误。

obfs试过stand alone模式和plugin模式。
nginx配置试过这两种，能和你的配置对比一下么？
谢谢！

nginx配置
server {
listen 80;
server_name ;

location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    proxy_http_version 1.1;
    proxy_set_header Upgrade "websocket";
    proxy_set_header Connection "upgrade";
    if (\$http_upgrade = "websocket") {
        proxy_pass http://127.0.0.1:9999;
    }
}
}

和

server {
listen 80;
server_name

location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:9999;
}
}

shadowsocks配置
{
"server": "127.0.0.1",
"server_port": 9999,
"password": "password",
"plugin": "obfs-server",
"plugin_opts": "obfs=http",
"timeout": 300,
"method": "xchacha20-ietf-poly1305",
"worker": 1
}

**Pull request merged**
