### PR TITLE
Travis + README.md Fix

### PR DESCRIPTION
**Pull request by LBYPatrick**
Add a little script for installing libsodium and fix README.md. Also comes with a Travis config, which is the one that passes the test.

### CODE REVIEW

**Comment by LBYPatrick** [comment]
@madeye

**Comment by madeye** [comment]
I've removed the dependency of libsodium. You may try again.

**Comment by LBYPatrick** [comment]
Thanks, I'll remove that.

**Comment by LBYPatrick** [comment]
@madeye

**Comment by madeye** [comment]
You need to reabse your branch to master branch first.

**Comment by LBYPatrick** [comment]
Just for a reminder, You need to enable travis-ci for this project in [Travis-Public-Projects](https://travis-ci.org) to make the config function properly.

**Pull request merged**
